fruits:
  - apple
  - pear
  - orange
  - kiwi

fruit-objects:
  - name: apple
    type: fruit
  - name: pear
    type: fruit
  - name: orange
    type: fruit
  - name: kiwi
    type: fruit